### ISSUE TITLE
Idéia

### ISSUE THREAD

**Issue by juanfariasdev** [tray-tecnologia/opencode-sdk#1]
Seria muito interessante ter a opção de trabalhar com o tema da tray localmente. Assim ficaria bem mais rápido o desenvolvimento usando o VScode ~Se já existir, peço desculpas

**Comment by rhandrade** [comment]
Olá @juanfariasdev, seria bem legal mesmo :+1:. Precisaríamos analisar para ver certinho se seria possível fazer isso. 

Acredito que essa ideia esteja mais relacionada com o CLI do que com o SDK. O SDK é responsável por fazer a comunicação com a Tray. Caso seja desenvolvimento local, o CLI quem deveria abrigar esse comportamento. 

Por favor, abre uma issue no repositório [Tray CLI](https://github.com/tray-tecnologia/tray-cli) para analisarmos melhor.

**Comment by juanfariasdev** [comment]
Beleza
